name: myaifriend
favicon: null
layout_spectrum: 0.48037
typography_spectrum: 0.71429
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4d6893'
    - '#f3ffff'
    - '#98c9e9'
    - '#a66b3f'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose:
  - name: awareness
    item: null
    url: null
